apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: some-cool-app
metadata:
  name: some-cool-app
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        app: some-cool-app
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      podSelector: {}
      policyTypes:
        - Ingress
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-api-to-patroni
      labels:
        app: some-cool-app
    spec:
      podSelector:
        matchLabels:
          cluster-name: patroni
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  component: api
          ports:
            - protocol: TCP
              port: 5432
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-api-to-minio
      labels:
        app: some-cool-app
    spec:
      podSelector:
        matchLabels:
          component: minio
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  component: api
          ports:
            - protocol: TCP
              port: 9000